export const MOCK_GRIEVANCES = [
  {
    id: "GRV-2024-1234",
    title: "Water supply disruption",
    category: "Water & Sanitation",
    description: "No water supply for 3 days in Sector 4, Lucknow",
    location: "Sector 4, Lucknow, Uttar Pradesh",
    status: "Resolved",
    date: "2024-01-15",
    lastUpdate: "2024-01-20",
    assignedTo: "Municipal Corporation",
    timeline: [
      { step: "Submitted", done: true, date: "Jan 15" },
      { step: "Received", done: true, date: "Jan 15" },
      { step: "Assigned", done: true, date: "Jan 16" },
      { step: "In Progress", done: true, date: "Jan 18" },
      { step: "Resolved", done: true, date: "Jan 20" },
    ],
  },
  {
    id: "GRV-2024-1235",
    title: "Road repair needed",
    category: "Roads & Infrastructure",
    description: "Large pothole on Main Market Road causing accidents",
    location: "Main Market Road, Lucknow, UP",
    status: "In Progress",
    date: "2024-01-18",
    lastUpdate: "2024-01-21",
    assignedTo: "PWD Department",
    timeline: [
      { step: "Submitted", done: true, date: "Jan 18" },
      { step: "Received", done: true, date: "Jan 18" },
      { step: "Assigned", done: true, date: "Jan 19" },
      { step: "In Progress", done: true, date: "Jan 21" },
      { step: "Resolved", done: false, date: "" },
    ],
  },
  {
    id: "GRV-2024-1236",
    title: "Street light not working",
    category: "Electricity",
    description: "Street lights on Gandhi Nagar Colony off for 1 week",
    location: "Gandhi Nagar, Lucknow, UP",
    status: "Pending",
    date: "2024-01-22",
    lastUpdate: "2024-01-22",
    assignedTo: "Pending Assignment",
    timeline: [
      { step: "Submitted", done: true, date: "Jan 22" },
      { step: "Received", done: true, date: "Jan 22" },
      { step: "Assigned", done: false, date: "" },
      { step: "In Progress", done: false, date: "" },
      { step: "Resolved", done: false, date: "" },
    ],
  },
  {
    id: "GRV-2024-1237",
    title: "Garbage not collected",
    category: "Sanitation",
    description: "Garbage not collected for 5 days near Bus Stand",
    location: "Bus Stand Area, Lucknow, UP",
    status: "Pending",
    date: "2024-01-23",
    lastUpdate: "2024-01-23",
    assignedTo: "Pending Assignment",
    timeline: [
      { step: "Submitted", done: true, date: "Jan 23" },
      { step: "Received", done: false, date: "" },
      { step: "Assigned", done: false, date: "" },
      { step: "In Progress", done: false, date: "" },
      { step: "Resolved", done: false, date: "" },
    ],
  },
  {
    id: "GRV-2024-1238",
    title: "School building roof damage",
    category: "Education",
    description: "Govt school roof leaking, children unable to study",
    location: "Primary School No. 5, Lucknow, UP",
    status: "In Progress",
    date: "2024-01-20",
    lastUpdate: "2024-01-24",
    assignedTo: "Education Department",
    timeline: [
      { step: "Submitted", done: true, date: "Jan 20" },
      { step: "Received", done: true, date: "Jan 20" },
      { step: "Assigned", done: true, date: "Jan 21" },
      { step: "In Progress", done: true, date: "Jan 24" },
      { step: "Resolved", done: false, date: "" },
    ],
  },
];

export const MOCK_SCHEMES = [
  {
    id: 1,
    name: "PM-KISAN",
    fullName: "Pradhan Mantri Kisan Samman Nidhi",
    benefit: "₹6,000/year",
    category: "Agriculture",
    eligibility: ["Farmer", "Land owner", "Aadhaar linked bank account"],
    documents: ["Aadhaar Card", "Land ownership papers", "Bank account details"],
    eligible: true,
    description: "Direct income support of ₹6,000/year to farmer families",
  },
  {
    id: 2,
    name: "PMJJBY",
    fullName: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    benefit: "₹2 Lakh life cover",
    category: "Insurance",
    eligibility: ["Age 18-50", "Bank account holder", "Aadhaar linked"],
    documents: ["Aadhaar Card", "Bank passbook", "Nominee details"],
    eligible: true,
    description: "Life insurance cover of ₹2 lakh at just ₹436/year",
  },
  {
    id: 3,
    name: "Ayushman Bharat",
    fullName: "Pradhan Mantri Jan Arogya Yojana",
    benefit: "₹5 Lakh health cover",
    category: "Health",
    eligibility: ["Below poverty line", "SECC database listed", "No private insurance"],
    documents: ["Aadhaar Card", "Ration Card", "Income certificate"],
    eligible: true,
    description: "Health insurance of ₹5 lakh per family per year",
  },
  {
    id: 4,
    name: "PMSBY",
    fullName: "Pradhan Mantri Suraksha Bima Yojana",
    benefit: "₹2 Lakh accident cover",
    category: "Insurance",
    eligibility: ["Age 18-70", "Savings bank account", "Aadhaar linked"],
    documents: ["Aadhaar Card", "Bank account details"],
    eligible: false,
    description: "Accidental death and disability cover for ₹20/year",
  },
];

export const ADMIN_STATS = {
  total: 1234,
  pending: 456,
  inProgress: 312,
  resolved: 778,
  todayNew: 23,
  avgResolutionDays: 4.2,
  categoryBreakdown: [
    { name: "Roads", value: 312, fill: "#22c55e" },
    { name: "Water", value: 278, fill: "#10b981" },
    { name: "Electricity", value: 198, fill: "#059669" },
    { name: "Sanitation", value: 156, fill: "#047857" },
    { name: "Others", value: 290, fill: "#065f46" },
  ],
  monthlyTrend: [
    { month: "Aug", submitted: 89, resolved: 72 },
    { month: "Sep", submitted: 102, resolved: 88 },
    { month: "Oct", submitted: 134, resolved: 98 },
    { month: "Nov", submitted: 118, resolved: 112 },
    { month: "Dec", submitted: 156, resolved: 134 },
    { month: "Jan", submitted: 189, resolved: 145 },
  ],
};

export const WHATSAPP_DEMO_FLOW = [
  { sender: "user", message: "🎤 [Voice message 0:08]", type: "voice", delay: 0 },
  {
    sender: "bot",
    message:
      "Namaste! 🙏 Mujhe aapki awaaz sun ke khushi hui. Main abhi AWS Transcribe se process kar raha hoon...",
    type: "text",
    delay: 1500,
  },
  {
    sender: "bot",
    message: "✅ Samajh gaya! Aap PM-KISAN ke baare mein jaanna chahte hain.",
    type: "text",
    delay: 3000,
  },
  {
    sender: "bot",
    message: "🤔 Quick sawaal: Kya aapke paas apni zameen hai?\n\nHaan | Nahi",
    type: "options",
    delay: 4500,
  },
  { sender: "user", message: "Haan", type: "text", delay: 6000 },
  {
    sender: "bot",
    message:
      "✅ Eligible!\n\n📋 PM-KISAN: ₹6,000/year\n📋 Kisan Credit Card\n\n📄 Documents needed:\n• Aadhaar Card\n• Land papers\n• Bank account\n\n🎤 [Voice reply in Hindi]",
    type: "result",
    delay: 7500,
  },
];
